### PR TITLE
fix typos in DE translation

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by peiying2** [comment]
@Bananeweizen thank you for reporting the errors. Could you make a suggestion in [Pontoon](https://pontoon.mozilla.org/de/firefox-relay-website/en/misc.ftl/?search=first-time-user-email-how-item-3-header&string=280157)? If you prefer not, I can make the suggestion and refer to this PR you created.

The reason we make suggestions directly through Pontoon so there is a record who suggested what. Let me know your preference.

**Comment by Bananeweizen** [comment]
@peiying2  Ah, didn't notice there is another website managing the primary data. I'd prefer not to create an account, so you could do that instead. Thanks a lot for the explanation.

**Comment by koehlermichael** [comment]
I just approved the fix on pontoon, @Bananeweizen & @peiying2 thanks for your report!

**Comment by peiying2** [comment]
@Bananeweizen the other change you suggested is from a different file no longer in Relay or Pontoon. It was migrated to mozilla.org but I couldn't find the string anymore. Consider this issue resolved. 

However, thanks to this PR, I realized we have some old files  that should have been removed after migration.

**Pull request closed without merging**
