### PR TITLE
Add missing string for nav-menu-mobile

### PR DESCRIPTION
**Pull request by lloan**

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]

**Comment by denyshon** [comment]
Could someone please explain what does this string mean and where is it placed?

**Comment by denyshon** [comment]
> Could someone please explain what does this string mean and where is it placed?
@lloan  @peiying2

**Comment by Vinnl** [comment]
That's a good question @denyshon. The string will be read to screen reader users when focusing the menu button on small screens. (I actually think "Menu" would probably have been a better caption, since the "Mobile" part isn't really relevant to the user and might actually be wrong if they've just resized their screen on desktop.)

**Comment by denyshon** [comment]
Thanks @Vinnl. So the string is a label for the main menu button in some cases. If it is, I also think "Menu" would be better as the user knows if his device is mobile and we shouldn't tell it to him (lengthening the string).

**Pull request merged**
