### PR TITLE
New string for Private Relay

### PR DESCRIPTION
**Pull request by Vinnl**
New string for https://github.com/mozilla/fx-private-relay/pull/1106.

### CODE REVIEW

**Comment by peiying2** [comment]
Hello @Vinnl thank you your interest in contributing to l10n. The correct process is to go through Pontoon: https://pontoon.mozilla.org/projects/firefox-relay-website/. You can create an account and contribute to the languages you are able to. This will create transparency on who did what and when, whether it's from staff or contributor, native speaker or not. If there are corrections, there is a history on the changes and it allows discussions for a particular string. Pontoon is a great tool for collaboration. I will close the PR because of this.

**Comment by Vinnl** [comment]
@peiying2 Just to make sure I've understood: that also holds for new strings? Or should I have only added the new string without adding en-GB and nl-NL translations (i.e. 8c02fedbb33deffad90e54e7c06ec2d0e0c9d5a5) as well?

**Comment by Vinnl** [comment]
Just in case it's that last option, I removed that commit - can always re-add it later if desired :)

**Comment by peiying2** [comment]
> Just in case it's that last option, I removed that commit - can always re-add it later if desired :)

Yes, we do need the new string, :). Thanks for the update. It looks good.

**Review by peiying2 — APPROVED** [review]

**Pull request merged**
